version: '3'

services:
  db:
    image: mariadb:10
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 127.0.0.1:3306:3306

volumes:
  db_data: {}
